export const SKILLS = [
    {
        name: "JavaScript",
        category: "Programming Languages",
        description: "Popular language for web development.",
        id: "javascript",
    },
    {
        name: "Python",
        category: "Programming Languages",
        description: "Versatile language used in web, data science, and scripting.",
        id: "python",
    },
    {
        name: "Java",
        category: "Programming Languages",
        description: "Widely used in enterprise applications.",
        id: "java",
    },
    {
        name: "C#",
        category: "Programming Languages",
        description: "Commonly used with the .NET framework.",
        id: "c#",
    },
    {
        name: "C++",
        category: "Programming Languages",
        description: "Used in systems programming and game development.",
        id: "c++",
    },
    {
        name: "Ruby",
        category: "Programming Languages",
        description: "Known for its simplicity and productivity.",
        id: "ruby",
    },
    {
        name: "PHP",
        category: "Programming Languages",
        description: "Popular for server-side web development.",
        id: "php",
    },
    {
        name: "Swift",
        category: "Programming Languages",
        description: "Primary language for iOS and macOS development.",
        id: "swift",
    },
    {
        name: "Kotlin",
        category: "Programming Languages",
        description: "Modern language for Android development.",
        id: "kotlin",
    },
    {
        name: "Go",
        category: "Programming Languages",
        description: "Known for its performance and simplicity in concurrent systems.",
        id: "go",
    },
    {
        name: "Rust",
        category: "Programming Languages",
        description: "Systems programming language with safety in mind.",
        id: "rust",
    },
    {
        name: "TypeScript",
        category: "Programming Languages",
        description: "A typed superset of JavaScript that compiles to plain JavaScript.",
        id: "typescript",
    },
    {
        name: "HTML",
        category: "Web Development",
        description: "Markup language for creating web pages.",
        id: "html",
    },
    {
        name: "CSS",
        category: "Web Development",
        description: "Stylesheet language for describing the presentation of web pages.",
        id: "css",
    },
    {
        name: "React",
        category: "Web Development",
        description: "Popular JavaScript library for building user interfaces.",
        id: "react",
    },
    {
        name: "Angular",
        category: "Web Development",
        description: "A framework for building client applications in HTML and TypeScript.",
        id: "angular",
    },
    {
        name: "Vue.js",
        category: "Web Development",
        description: "Progressive JavaScript framework for building UIs.",
        id: "vue.js",
    },
    {
        name: "Node.js",
        category: "Web Development",
        description: "JavaScript runtime built on Chrome's V8 engine.",
        id: "node.js",
    },
    {
        name: "Express",
        category: "Web Development",
        description: "Minimalist web framework for Node.js.",
        id: "express",
    },
    {
        name: "Django",
        category: "Web Development",
        description: "High-level Python web framework.",
        id: "django",
    },
    {
        name: "Flask",
        category: "Web Development",
        description: "Lightweight Python web framework.",
        id: "flask",
    },
    {
        name: "ASP.NET",
        category: "Web Development",
        description: "Framework for building modern web apps using .NET.",
        id: "asp.net",
    },
    {
        name: "iOS Development",
        category: "Mobile Development",
        description: "Development of apps for Apple's iOS platform.",
        id: "ios-development",
    },
    {
        name: "Android Development",
        category: "Mobile Development",
        description: "Development of apps for Android devices.",
        id: "android-development",
    },
    {
        name: "React Native",
        category: "Mobile Development",
        description: "Framework for building native apps using React.",
        id: "react-native",
    },
    {
        name: "Flutter",
        category: "Mobile Development",
        description: "UI toolkit for crafting natively compiled applications.",
        id: "flutter",
    },
    {
        name: "MongoDB",
        category: "Databases",
        description: "NoSQL database known for scalability and flexibility.",
        id: "mongodb",
    },
    {
        name: "MySQL",
        category: "Databases",
        description: "Popular open-source relational database.",
        id: "mysql",
    },
    {
        name: "PostgreSQL",
        category: "Databases",
        description: "Advanced open-source relational database.",
        id: "postgresql",
    },
    {
        name: "SQL Server",
        category: "Databases",
        description: "Relational database by Microsoft.",
        id: "sql-server",
    },
    {
        name: "Oracle",
        category: "Databases",
        description: "Enterprise-grade relational database.",
        id: "oracle",
    },
    {
        name: "Redis",
        category: "Databases",
        description:
            "In-memory data structure store used as a database, cache, and message broker.",
        id: "redis",
    },
    {
        name: "AWS",
        category: "DevOps & Cloud",
        description: "Amazon Web Services cloud platform.",
        id: "aws",
    },
    {
        name: "Microsoft Azure",
        category: "DevOps & Cloud",
        description: "Cloud computing service by Microsoft.",
        id: "microsoft-azure",
    },
    {
        name: "Google Cloud Platform (GCP)",
        category: "DevOps & Cloud",
        description: "Cloud computing service by Google.",
        id: "google-cloud-platform-(gcp)",
    },
    {
        name: "Docker",
        category: "DevOps & Cloud",
        description: "Platform for containerizing applications.",
        id: "docker",
    },
    {
        name: "Kubernetes",
        category: "DevOps & Cloud",
        description: "Container orchestration system.",
        id: "kubernetes",
    },
    {
        name: "Jenkins",
        category: "DevOps & Cloud",
        description: "Automation server for CI/CD.",
        id: "jenkins",
    },
    {
        name: "CI/CD Pipelines",
        category: "DevOps & Cloud",
        description: "Practice of automating code integration and deployment.",
        id: "ci/cd-pipelines",
    },
    {
        name: "Git & Version Control",
        category: "Tools & Practices",
        description: "Tool for source code management.",
        id: "git-&-version-control",
    },
    {
        name: "RESTful APIs",
        category: "Tools & Practices",
        description: "Design style for web services.",
        id: "restful-apis",
    },
    {
        name: "GraphQL",
        category: "Tools & Practices",
        description: "Query language for APIs.",
        id: "graphql",
    },
    {
        name: "Microservices",
        category: "Tools & Practices",
        description:
            "Architectural style structuring an application as a collection of loosely coupled services.",
        id: "microservices",
    },
    {
        name: "Agile & Scrum",
        category: "Tools & Practices",
        description: "Methodologies for iterative development.",
        id: "agile-&-scrum",
    },
    {
        name: "Test-Driven Development (TDD)",
        category: "Tools & Practices",
        description: "Development process relying on short, repetitive development cycles.",
        id: "test-driven-development-(tdd)",
    },
    {
        name: "Continuous Integration/Continuous Deployment",
        category: "Tools & Practices",
        description: "Practice of frequently integrating and deploying code changes.",
        id: "continuous-integration/continuous-deployment",
    },
    {
        name: "Data Analysis (Pandas, NumPy)",
        category: "Data Science & Machine Learning",
        description: "Data manipulation and analysis libraries in Python.",
        id: "data-analysis-(pandas,-numpy)",
    },
    {
        name: "Machine Learning (TensorFlow, PyTorch, scikit-learn)",
        category: "Data Science & Machine Learning",
        description: "Libraries and frameworks for machine learning.",
        id: "machine-learning-(tensorflow,-pytorch,-scikit-learn)",
    },
    {
        name: "Data Visualization",
        category: "Data Science & Machine Learning",
        description: "Techniques and tools for visual representation of data.",
        id: "data-visualization",
    },
    {
        name: "R Programming",
        category: "Data Science & Machine Learning",
        description: "Programming language used for statistical computing and graphics.",
        id: "r-programming",
    },
    {
        name: "Network Security",
        category: "Cybersecurity",
        description: "Practices to protect networks from unauthorized access.",
        id: "network-security",
    },
    {
        name: "Ethical Hacking",
        category: "Cybersecurity",
        description: "Legitimate probing for security weaknesses.",
        id: "ethical-hacking",
    },
    {
        name: "Penetration Testing",
        category: "Cybersecurity",
        description: "Testing methods to evaluate security.",
        id: "penetration-testing",
    },
    {
        name: "Cryptography",
        category: "Cybersecurity",
        description: "Techniques for secure communication.",
        id: "cryptography",
    },
    {
        name: "Agile, Scrum, Kanban",
        category: "Project Management",
        description: "Methodologies for iterative project management.",
        id: "agile,-scrum,-kanban",
    },
    {
        name: "Waterfall",
        category: "Project Management",
        description: "Traditional project management methodology.",
        id: "waterfall",
    },
    {
        name: "Risk Management",
        category: "Business & Management",
        description: "Identifying, assessing, and controlling risks.",
        id: "risk-management",
    },
    {
        name: "Strategic Planning",
        category: "Business & Management",
        description: "Long-term planning for business objectives.",
        id: "strategic-planning",
    },
    {
        name: "Business Analysis",
        category: "Business & Management",
        description: "Evaluating business needs and solutions.",
        id: "business-analysis",
    },
    {
        name: "Process Improvement",
        category: "Operations",
        description: "Optimizing processes for efficiency.",
        id: "process-improvement",
    },
    {
        name: "Supply Chain Management",
        category: "Operations",
        description: "Managing the flow of goods and services.",
        id: "supply-chain-management",
    },
    {
        name: "Quality Assurance",
        category: "Operations",
        description: "Ensuring products meet quality standards.",
        id: "quality-assurance",
    },
    {
        name: "Team Leadership",
        category: "Leadership & Management",
        description: "Leading teams effectively.",
        id: "team-leadership",
    },
    {
        name: "Conflict Resolution",
        category: "Leadership & Management",
        description: "Resolving disputes and conflicts.",
        id: "conflict-resolution",
    },
    {
        name: "Change Management",
        category: "Leadership & Management",
        description: "Managing transitions in business.",
        id: "change-management",
    },
    {
        name: "SEO (Search Engine Optimization)",
        category: "Digital Marketing",
        description: "Optimizing web content for search engines.",
        id: "seo-(search-engine-optimization)",
    },
    {
        name: "SEM (Search Engine Marketing)",
        category: "Digital Marketing",
        description: "Marketing through search engines.",
        id: "sem-(search-engine-marketing)",
    },
    {
        name: "Content Marketing",
        category: "Digital Marketing",
        description: "Creating valuable content to attract customers.",
        id: "content-marketing",
    },
    {
        name: "Social Media Marketing",
        category: "Digital Marketing",
        description: "Using social platforms for marketing.",
        id: "social-media-marketing",
    },
    {
        name: "Email Marketing",
        category: "Digital Marketing",
        description: "Direct marketing using email.",
        id: "email-marketing",
    },
    {
        name: "Analytics & Data-driven Marketing",
        category: "Digital Marketing",
        description: "Using data analytics for marketing decisions.",
        id: "analytics-&-data-driven-marketing",
    },
    {
        name: "Lead Generation",
        category: "Sales",
        description: "Identifying potential customers.",
        id: "lead-generation",
    },
    {
        name: "Customer Relationship Management (CRM)",
        category: "Sales",
        description: "Managing customer interactions.",
        id: "customer-relationship-management-(crm)",
    },
    {
        name: "Negotiation",
        category: "Sales",
        description: "Discussing terms to reach an agreement.",
        id: "negotiation",
    },
    {
        name: "Market Research",
        category: "Sales",
        description: "Gathering and analyzing market data.",
        id: "market-research",
    },
    {
        name: "Branding",
        category: "Creative & Branding",
        description: "Creating and managing brand identity.",
        id: "branding",
    },
    {
        name: "Copywriting",
        category: "Creative & Branding",
        description: "Writing persuasive marketing text.",
        id: "copywriting",
    },
    {
        name: "Public Relations",
        category: "Creative & Branding",
        description: "Managing public image and communications.",
        id: "public-relations",
    },
    {
        name: "Financial Analysis",
        category: "Finance & Accounting",
        description: "Evaluating financial data.",
        id: "financial-analysis",
    },
    {
        name: "Budgeting & Forecasting",
        category: "Finance & Accounting",
        description: "Planning financial budgets and forecasts.",
        id: "budgeting-&-forecasting",
    },
    {
        name: "Accounting Principles",
        category: "Finance & Accounting",
        description: "Fundamental accounting practices.",
        id: "accounting-principles",
    },
    {
        name: "Taxation",
        category: "Finance & Accounting",
        description: "Managing tax-related matters.",
        id: "taxation",
    },
    {
        name: "Auditing",
        category: "Finance & Accounting",
        description: "Examining financial records.",
        id: "auditing",
    },
    {
        name: "Investment Analysis",
        category: "Finance & Accounting",
        description: "Assessing investment opportunities.",
        id: "investment-analysis",
    },
    {
        name: "Risk & Compliance",
        category: "Finance & Accounting",
        description: "Managing risk and regulatory requirements.",
        id: "risk-&-compliance",
    },
    {
        name: "Graphic Design",
        category: "Design & Creative",
        description: "Creating visual content.",
        id: "graphic-design",
    },
    {
        name: "UI/UX Design",
        category: "Design & Creative",
        description: "Designing user interfaces and experiences.",
        id: "ui/ux-design",
    },
    {
        name: "Web Design",
        category: "Design & Creative",
        description: "Designing websites.",
        id: "web-design",
    },
    {
        name: "Mobile App Design",
        category: "Design & Creative",
        description: "Designing mobile applications.",
        id: "mobile-app-design",
    },
    {
        name: "Adobe Photoshop",
        category: "Design & Creative",
        description: "Image editing and graphic design software.",
        id: "adobe-photoshop",
    },
    {
        name: "Adobe Illustrator",
        category: "Design & Creative",
        description: "Vector graphic design software.",
        id: "adobe-illustrator",
    },
    {
        name: "Adobe InDesign",
        category: "Design & Creative",
        description: "Desktop publishing software.",
        id: "adobe-indesign",
    },
    {
        name: "Sketch",
        category: "Design & Creative",
        description: "Digital design toolkit.",
        id: "sketch",
    },
    {
        name: "Figma",
        category: "Design & Creative",
        description: "Collaborative interface design tool.",
        id: "figma",
    },
    {
        name: "Video Editing",
        category: "Design & Creative",
        description: "Editing video content.",
        id: "video-editing",
    },
    {
        name: "Animation",
        category: "Design & Creative",
        description: "Creating animated content.",
        id: "animation",
    },
    {
        name: "Motion Graphics",
        category: "Design & Creative",
        description: "Animated graphic design.",
        id: "motion-graphics",
    },
    {
        name: "Talent Acquisition",
        category: "Human Resources",
        description: "Sourcing and hiring talent.",
        id: "talent-acquisition",
    },
    {
        name: "Employee Engagement",
        category: "Human Resources",
        description: "Improving employee satisfaction.",
        id: "employee-engagement",
    },
    {
        name: "Performance Management",
        category: "Human Resources",
        description: "Evaluating employee performance.",
        id: "performance-management",
    },
    {
        name: "Training & Development",
        category: "Human Resources",
        description: "Employee skill development.",
        id: "training-&-development",
    },
    {
        name: "HR Information Systems (HRIS)",
        category: "Human Resources",
        description: "Managing HR data with technology.",
        id: "hr-information-systems-(hris)",
    },
    {
        name: "Technical Writing",
        category: "Writing & Communication",
        description: "Writing technical documentation.",
        id: "technical-writing",
    },
    {
        name: "Content Writing",
        category: "Writing & Communication",
        description: "Creating engaging written content.",
        id: "content-writing",
    },
    {
        name: "Copywriting",
        category: "Writing & Communication",
        description: "Persuasive writing for marketing.",
        id: "copywriting",
    },
    {
        name: "Editing & Proofreading",
        category: "Writing & Communication",
        description: "Refining and correcting text.",
        id: "editing-&-proofreading",
    },
    {
        name: "Public Speaking",
        category: "Communication",
        description: "Delivering presentations to an audience.",
        id: "public-speaking",
    },
    {
        name: "Presentation Skills",
        category: "Communication",
        description: "Effective techniques for delivering presentations.",
        id: "presentation-skills",
    },
    {
        name: "Interpersonal Communication",
        category: "Communication",
        description: "Effective personal interaction skills.",
        id: "interpersonal-communication",
    },
    {
        name: "Customer Relationship Management",
        category: "Customer Service",
        description: "Managing customer interactions and relationships.",
        id: "customer-relationship-management",
    },
    {
        name: "Conflict Resolution",
        category: "Customer Service",
        description: "Resolving customer issues and disputes.",
        id: "conflict-resolution",
    },
    {
        name: "Empathy & Active Listening",
        category: "Customer Service",
        description: "Understanding and addressing customer needs.",
        id: "empathy-&-active-listening",
    },
    {
        name: "Patient Care",
        category: "Healthcare",
        description: "Providing care and support to patients.",
        id: "patient-care",
    },
    {
        name: "Medical Coding",
        category: "Healthcare",
        description: "Translating medical procedures into codes.",
        id: "medical-coding",
    },
    {
        name: "Healthcare Administration",
        category: "Healthcare",
        description: "Managing healthcare facilities and operations.",
        id: "healthcare-administration",
    },
    {
        name: "Clinical Research",
        category: "Healthcare",
        description: "Conducting research in clinical settings.",
        id: "clinical-research",
    },
    {
        name: "Contract Law",
        category: "Legal",
        description: "Understanding and drafting contracts.",
        id: "contract-law",
    },
    {
        name: "Legal Research",
        category: "Legal",
        description: "Researching legal precedents and regulations.",
        id: "legal-research",
    },
    {
        name: "Compliance & Regulatory Affairs",
        category: "Legal",
        description: "Ensuring adherence to laws and regulations.",
        id: "compliance-&-regulatory-affairs",
    },
    {
        name: "Intellectual Property",
        category: "Legal",
        description: "Managing intellectual property rights.",
        id: "intellectual-property",
    },
    {
        name: "Negotiation",
        category: "Legal",
        description: "Negotiating agreements and contracts.",
        id: "negotiation",
    },
    {
        name: "Problem Solving",
        category: "Soft Skills",
        description: "Identifying and resolving issues.",
        id: "problem-solving",
    },
    {
        name: "Critical Thinking",
        category: "Soft Skills",
        description: "Analyzing facts to form a judgment.",
        id: "critical-thinking",
    },
    {
        name: "Leadership",
        category: "Soft Skills",
        description: "Guiding and motivating a team.",
        id: "leadership",
    },
    {
        name: "Teamwork",
        category: "Soft Skills",
        description: "Collaborating effectively with others.",
        id: "teamwork",
    },
    {
        name: "Time Management",
        category: "Soft Skills",
        description: "Efficiently managing one’s time.",
        id: "time-management",
    },
    {
        name: "Adaptability",
        category: "Soft Skills",
        description: "Adjusting to new challenges.",
        id: "adaptability",
    },
    {
        name: "Creativity",
        category: "Soft Skills",
        description: "Thinking outside the box.",
        id: "creativity",
    },
    {
        name: "Analytical Thinking",
        category: "Soft Skills",
        description: "Systematically solving problems.",
        id: "analytical-thinking",
    },
    {
        name: "Emotional Intelligence",
        category: "Soft Skills",
        description: "Understanding and managing emotions.",
        id: "emotional-intelligence",
    },
    {
        name: "CAD (Computer-Aided Design)",
        category: "Mechanical Engineering",
        description: "Designing with computer assistance.",
        id: "cad-(computer-aided-design)",
    },
    {
        name: "SolidWorks",
        category: "Mechanical Engineering",
        description: "3D CAD design software.",
        id: "solidworks",
    },
    {
        name: "Finite Element Analysis (FEA)",
        category: "Mechanical Engineering",
        description: "Simulation for stress and strain analysis.",
        id: "finite-element-analysis-(fea)",
    },
    {
        name: "Circuit Design",
        category: "Electrical Engineering",
        description: "Designing electrical circuits.",
        id: "circuit-design",
    },
    {
        name: "PLC Programming",
        category: "Electrical Engineering",
        description: "Programming for industrial control systems.",
        id: "plc-programming",
    },
    {
        name: "Embedded Systems",
        category: "Electrical Engineering",
        description: "Designing systems with integrated computing.",
        id: "embedded-systems",
    },
    {
        name: "AutoCAD",
        category: "Civil & Structural Engineering",
        description: "Design and drafting software.",
        id: "autocad",
    },
    {
        name: "Structural Analysis",
        category: "Civil & Structural Engineering",
        description: "Analysis of building structures.",
        id: "structural-analysis",
    },
    {
        name: "Project Management",
        category: "Civil & Structural Engineering",
        description: "Managing engineering projects.",
        id: "project-management",
    },
    {
        name: "Process Engineering",
        category: "Chemical Engineering",
        description: "Optimizing chemical processes.",
        id: "process-engineering",
    },
    {
        name: "Quality Control",
        category: "Chemical Engineering",
        description: "Ensuring product quality.",
        id: "quality-control",
    },
    {
        name: "Chemical Process Simulation",
        category: "Chemical Engineering",
        description: "Modeling chemical processes.",
        id: "chemical-process-simulation",
    },
];

export const SKILLCATEGORIES = [...new Set(SKILLS.map((skill) => skill.category))].map(
    (category) => ({ id: category.trim().toLowerCase(), name: category }),
);
